export const CUSTOMER_STATUSES = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  ON_HOLD: "ON_HOLD",
  BLACKLISTED: "BLACKLISTED",
} as const;

export const LEAD_STATUSES = {
  NEW: "NEW",
  CONTACTED: "CONTACTED",
  QUALIFIED: "QUALIFIED",
  UNQUALIFIED: "UNQUALIFIED",
  CONVERTED: "CONVERTED",
} as const;

export const OPPORTUNITY_STAGES = {
  PROSPECTING: "PROSPECTING",
  NEGOTIATION: "NEGOTIATION",
  QUOTED: "QUOTED",
  PENDING_DECISION: "PENDING_DECISION",
  CLOSED_WON: "CLOSED_WON",
  CLOSED_LOST: "CLOSED_LOST",
} as const;

export const QUOTE_STATUSES = {
  DRAFT: "DRAFT",
  SENT: "SENT",
  VIEWED: "VIEWED",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
} as const;

export const ACTIVITY_TYPES = {
  CALL: "CALL",
  VISIT: "VISIT",
  EMAIL: "EMAIL",
  VIBER: "VIBER",
} as const;

export const COMPLAINT_CATEGORIES = {
  DAMAGED: "DAMAGED",
  LATE: "LATE",
  WRONG_PART: "WRONG_PART",
  PRICING: "PRICING",
  OTHER: "OTHER",
} as const;

export const CUSTOMER_TYPES = {
  WHOLESALE: "WHOLESALE",
  RETAILER: "RETAILER",
  MECHANIC_SHOP: "MECHANIC_SHOP",
  FLEET: "FLEET",
  WALK_IN: "WALK_IN",
  ONLINE: "ONLINE",
} as const;
